# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TaskManagment' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TaskManagment
  pod 'RealmSwift', '~> 0.98'

  target 'TaskManagmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TaskManagmentUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
